
export const SUBMIT_REVIEW_REQUEST = "SUBMIT_REVIEW_REQUEST";
export const SUBMIT_REVIEW_SUCCESS = "SUBMIT_REVIEW_SUCCESS";
export const SUBMIT_REVIEW_FAILURE = "SUBMIT_REVIEW_FAILURE";
// ActionTypes.js
export const GET_ALL_RATINGS_REVIEWS_REQUEST = 'GET_ALL_RATINGS_REVIEWS_REQUEST';
export const GET_ALL_RATINGS_REVIEWS_SUCCESS = 'GET_ALL_RATINGS_REVIEWS_SUCCESS';
export const GET_ALL_RATINGS_REVIEWS_FAILURE = 'GET_ALL_RATINGS_REVIEWS_FAILURE';
