export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';


export const GET_ORDER_BY_ID_ORDER_REQUEST = "GET_ORDER_BY_ID_ORDER_REQUEST";
export const GET_ORDER_BY_ID_ORDER_SUCCESS = "GET_ORDER_BY_ID_ORDER_SUCCESS";
export const GET_ORDER_BY_ID_ORDER_FAILURE = "GET_ORDER_BY_ID_ORDER_FAILURE";


export const GET_ORDER_HISTORY_REQUEST = "GET_ORDER_HISTORY_REQUEST";
export const GET_ORDER_HISTORY_SUCCESS = "GET_ORDER_HISTORY_SUCCESS";
export const GET_ORDER_HISTORY_FAILURE = "GET_ORDER_HISTORY_FAILURE";

export const GET_ORDERS_BY_USER_ID_REQUEST = "GET_ORDERS_BY_USER_ID_REQUEST";
export const GET_ORDERS_BY_USER_ID_SUCCESS = "GET_ORDERS_BY_USER_ID_SUCCESS";
export const GET_ORDERS_BY_USER_ID_FAILURE = "GET_ORDERS_BY_USER_ID_FAILURE";


export const FIND_ORDERS_REQUEST = "FIND_ORDERS_REQUEST";
export const FIND_ORDERS_SUCCESS = "FIND_ORDERS_SUCCESS";
export const FIND_ORDERS_FAILURE = "FIND_ORDERS_FAILURE"